### ISSUE TITLE
[Bug]: Chip cards template does not show value "0"

### ISSUE THREAD

**Issue by joaopedros2** [piitaya/lovelace-mushroom#1025]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

I have a sensor template that groups the state of several lights to tell me the number of lights on.  When the sensor is indicating "0" the chip card template ignores the value and does not display anything.  when it passes to another value the number appears.  I use the following code that tries to force the appearance of "0" and it still doesn't work. 
```
{% set status = states.sensor.parents_room_lights_on.state %}
 {% if status > '0' %}
 {{ status }}
 {% else %}
 {{ '0' }}
 {% endif %}
```

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser:
- HA Version:
- Mushroom:
```

**Comment by FHeilmann** [comment]
Same here. States that evaluate to '0' result in no state shown.

**Comment by JRascagneres** [comment]
Not overly helpful but I worked around this by adding a string to the output

**Comment by piitaya** [comment]
Should be fine with the latest update ☺️

**Comment by twodrops** [comment]
Thanks for fixing this bug. I was however "misusing" this bug 😸 This bug was useful when there were too many chip cards and most of them stay at 0 most of the time. This used to save a lot of space (without the 0) and prevent the cards from wrapping to the next line. Also for certain usecases like "Number of days until next waste collection", it was nice to see the card without a 0, when the waste collection was "today".
I can achieve the same with templates now, but the bug had made easier 😄
