### ISSUE TITLE
A climate card

### ISSUE THREAD

**Issue by hcoohb** [piitaya/lovelace-mushroom#107]
Is there any plan for a climate card?
Love the mushroom cards and a climate/thermostat card would be a great addition to the current cards.
As the official HA is really huge and very different looking on the dashboard.

Thanks!

**Comment by brandensilva** [comment]
The README docs indicate there is a climate card planned in the future. 

I think we should move towards this look which is where the mushroom design is inspired from with Yuhang's design work on Behance:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/200190/154092599-d7a9f92d-a3e7-4475-ba27-1fdd17a5d256.png">

The + and - are a nice addition over the typical climate change cards because I find it to be rare to extend the temperature more than a couple degrees for my use cases. This is way easier to tap a couple times than trying to move the circular inputs.

**Comment by hcoohb** [comment]
Oh, sorry, I missed the line on the readme. My bad.

Now if we are discussing design, like you said, use case to modify temperatures by ore than a few degrees are probably extremely rare.
So personally I do not think the design from Yuhang that keeps the sliding circle around the value makes much sense and it visually breaks from other controls.
To keep in line with current design of light card, I think, we could have the controls on a second line.
Selecting a prefered mode on the card ui editor, let you turn on/off by clicking on the icon. And then if you want to switch to other mode, icons on second line let you do so.

Here is what I coded using button-card for now, that matches my other mushroom-card themes:
![image](https://user-images.githubusercontent.com/12975783/154389218-3fe0ab75-a612-4a3d-80c8-00b19e9ae39a.png)
![image](https://user-images.githubusercontent.com/12975783/154388381-827fc2a2-43c9-49bb-b809-c04fdbcf716e.png)

**Comment by zsarnett** [comment]
I would recommend not working with the Round Slider. (as the one who built it for HA its not worth it and the UX isn't great)

**Comment by brandensilva** [comment]
@zsarnett Yeah it's a nice visual but I can definitely see how the UX isn't strong. What I do like about it perhaps though is it gives a wee bit of perspective from a top view of the low and highs and where the current temperature target falls. It doesn't help you any really in knowing what to set the temp, but it gives perspective. 

@hcoohb This seems like a good start. I think part of the goal should be to get something unique looking still if we can so it stands out from all the other cards while maintaining usability. 

Perhaps an improvement is making sure we are still calling out those temperatures more clearly with larger font sizes. This could be on a tablet and seen from a distance (think like a Nest or Ecobee how they call out the temps with large font sizes clearly)

I wonder if we can come up with a decent concept around layout modes that works in each of those situations while still giving it uniqueness. I do think we should keep the + and - for those quick temp adjustments.

I'll see if I can throw some concepts together soon on this too. I still need to get this in Figma or Framer sometime for faster iterations.

**Comment by hcoohb** [comment]
> > Here is what I coded using button-card for now, that matches my other mushroom-card themes:
> 
> @hcoohb care to share the code for that? You might also want to install [mushroom-theme](https://github.com/piitaya/lovelace-mushroom-themes) (if you haven't already, I can't really tell) to make it even more mushroom looking.

@antonio1475 Here is the repo where I documented what I am using: [hcoohb/lovelace-mushroom-button-card](https://github.com/hcoohb/lovelace-mushroom-button-card).
Very adapted to my use-case for now but happy to open up.

**Comment by brandensilva** [comment]
I decided to spend some time last weekend to work on getting mushroom cards added to design land. I have more cards to add but took an initial stab at a basic climate card that incorporates many of mushrooms existing design elements with a push for some slightly different elements.

There are a lot of assumed user needs to consider which I'll outline here:

- Users will be either warm or cold in a given moment and want to make incremental adjustments to temperatures more often than large temperature changes to increase their comfort. 

- Users have a schedule or routine for large temperature adjustments and settings which is managed outside of the thermostat card.

- Before a user can know what to set the temperature to, you need to know what the temperature is and what state the thermostat is in to make a decision on how to fix their comfort issues.

- Changing modes is most common during seasonal changes and is rare. (e.g In winter heat mode is expected to be used. In spring dual mode is used. In summer the cold mode and fan mode is used ).

- Auxillary functions are used less than often than functions (Auxillary examples e.g Humidifier, fan)

- Users of this group would prefer to keep things true to the Mushroom look and feel

- Users of this group probably want layout flexibility between vertical, horizontal, or default to accommodate their dashboard layouts.

- Users may use this on mobile, tablet, or desktop given HA's flexibility so it is important that controls are built for fingers and pointer devices.

There are two modes modes of thinking when working with temperatures from the most popular thermostats:

The Nest approach: Users only have control over the target temperature so that number is large and emphasized. The current temperature is small and adjusted by rotating (3rd gen) or sliding finger along on the edge (4th gen). 

The Ecobee approach: Current temperature is large and emphasized, the target temps are shown as a range to the side. Adjust the range up or down via finger vertically on thermostat.

I've chosen to opt for the Nest approach to displaying information give that users only have control over what they set the temperature too and not the current temperature. 

Given all this, I've designed around these points while maintaining the design language, mushroom look and feel and HA thermostat/climiate capabilities, and adapting to these user needs.

I'll post some screenshots and a prototype in my next comment when I get a moment.

**Comment by brandensilva** [comment]
In vertical mode I moved the status badge down under the target temperature, but it could also live up with the default entity approach

Also, we can drop the padding on the badge when "off" to better align it with the current temperature. Idle could work the same way since "idle" and "off" are the same concept.

Some other things to add and points to consider:
- Add Dual, Fan, and Humidifier modes
- Off mode
- Space constraints

I'm working through the other modes now on how those might work but probably better to release something we can start using something and gathering feedback without going overly deep in solving everything now.

**Dual Mode**

Dual mode involves two temperatures (low and high). We could match the Nest approach on this and that works for vertical but it would be an issue perhaps on the other layout modes. I'll toy around with it to see if we can lower the font size and make it work.

**Fan Mode**

I believe this just supports on and off (at least for my thermostat). Let me know if any of you have speed controls on yours.

**Humidifier Mode**

Would display the humidity. Nest has an on/off switch for me in their app, and allows you to set a minimum target to be above. Not sure if HA supports that though as I haven't gotten it to work yet fully. Less familiar with other thermostats so curious to how others humidifiers work.

**Off Mode**

I have it setting the target temp to sync with the current temperature in off mode. This should allow users walking by a tablet on a wall to see the current temperature more boldy if in off mode. I rarely use off mode in my own house but could see myself using it more if it allowed this.

**Space Constraints**

Given that when we add more modes we will have a more challenging time with the horizontal layout and cannot squeeze this all into smaller form factors, we will want to come up with a solution to adapting to this situation. I have an idea that I will share soon on it but the short answer is dropping into a "collapsed" mode that treats the action bar as a select dropdown instead of a radio would help.

It would also be beneficial if we can allow at least 2 or 3 temperature controls to be stacked together like so but we lose out on changing modes but can see the mode with the icon badge that exists in Mushroom today:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/200190/156598566-9eedc2a8-4935-4e26-a502-502913012139.png">


Anyhow, would love to hear your thoughts. Does this address a lot of the assumptions we want out of this?

**Comment by zsarnett** [comment]
The biggest issue is Auto Mode. Auto Mode throws out just about every design haha

**Comment by zsarnett** [comment]
But these look great. I like the simple design and Mobile friendliness! Great job on this. The last image you have there with the +and - and the grey background is a nice touch

**Comment by brandensilva** [comment]
Yeah I'm thinking through auto mode (which I assume is dual-mode) now.

It will work in vertical. It's possible we can get it to work in other layout modes too but we'd have to get creative.

**Comment by zsarnett** [comment]
Yea. The vertical could work. I think the only way is the make it taller or make a switch of some kind. So the buttons icons turn red or blue based on what mode you are changing

**Comment by brandensilva** [comment]
> But these look great. I like the simple design and Mobile friendliness! Great job on this. The last image you have there with the +and - and the grey background is a nice touch

Thanks! I've also added some desktop friendliness because I find that lacking in cards today. I use Home Assistant app for my iMac in a mobile form factor but don't get the benefits of hover and click states. So you'll notice the action buttons have a box shadow darken on hover and when tapping they flash. 

I will add the icons for the action bar soon too so they have a hover state.

**Comment by piitaya** [comment]
Nice inspirations 🙂 Thank for the proposal. It's very clean ! Great work 🙂

I think the most difficult part is the layout part and the responsive part
For example, in the current Mushroom design, in horizontal mode, the card info and controls are 50% - 50%. On vertical mode, the icon is above the name, not on the left.
We tried to make mushroom the more composable and reusable possible in term of coding so there is big constraints.

Currently, Mushroom design is very "minimalist" with small cards, few information and only one control at a time. Your vertical mode look like a detail or something we can have in a popup for example. Maybe we should consider in the future to have a big card layout with all the controls visible.

For the modes, there is `hvac` mode and `preset` mode. It can be a big challenge to integrate presets too.

For the shadow around buttons, I think that looks strange to have a button with shadow inside a card with card. On the behance design, the round button with shadow are used when there is no card. Don't you think we can flatten the components inside the card ?

Finally, I like the label idea to display thermostat state. I can be good to use it to format additional information on others cards like the brightness for light or the speed for fan.

For the first version, I don't think it's a good idea to have multiple controls visible at a time because it will not be possible to have this card integrated in a layout card like this : 
![image](https://user-images.githubusercontent.com/5878303/156615483-572dcd3a-1dfe-4877-976e-849d2c122d54.png)

**Comment by brandensilva** [comment]
> Nice inspirations 🙂 Thank for the proposal. It's very clean ! Great work 🙂

Hey thanks, wanted to contribute! And thanks for your work on Mushroom.

> 
> I think the most difficult part is the layout part and the responsive part For example, in the current Mushroom design, in horizontal mode, the card info and controls are 50% - 50%. 

That's where I'm talking about adapting the action bar to be in a collapsed dropdown mode for tighter space constraints. I'll show this soon but it does give it flexibility to work in different space constrained situations.

> On vertical mode, the icon is above the name, not on the left. We tried to make mushroom the more composable and reusable possible in term of coding so there is big constraints.

Yeah I was aware of that when designing this out but wanted to show a more compact form. We can easily have that card take more vertical space to keep it similar but we should be mindful of taking the least amount of space possible on a users dashboard to achieving a given task if we can. If that means breaking some constraints for a better user experience, I think that is sometimes acceptable but totally understand where you are coming from.
 
> Currently, Mushroom design is very "minimalist" with small cards, few information and only one control at a time. Your vertical mode look like a detail or something we can have in a popup for example. Maybe we should consider in the future to have a big card layout with all the controls visible.

This is a minimalist look that appeals to different use cases in the environments at which a temperature control can be consumed.

For example, in tablet view the vertical mode in this case is the most usable form of this component. Right now UI Minimalist and Mushroom are very mobile heavy, and that's fine, but it isn't the only way this library will be consumed. I know when I start getting my dashboard tablet ready I'm going to want more options to adapt Mushroom to that form factor.

I think the popup can be even more advanced personally and what is shown here covers the basics of the most used functionality (once auto, fan, and humidifier modes are added). But you are right, some of this could be offloaded into a popup card. I just know that isn't supported in Mushroom right now so went with a solution that covers most use cases.

> 
> For the modes, there is `hvac` mode and `preset` mode. It can be a big challenge to integrate presets too.

I'm unfamiliar with these modes as of yet. What does hvac and preset do?

> 
> For the shadow around buttons, I think that looks strange to have a button with shadow inside a card with card. On the behance design, the round button with shadow are used when there is no card. Don't you think we can flatten the components inside the card ?

I don't think this an issue really but totally hear your opinion on it. The shadows purpose is to indicate an interactive element by protruding outside of a non-interactive element. Not all cards are meant to be tappable and can house interactive elements within them. In fact I think more should do this as long as they adhere to better tap sizes. The shadow is one way to have them stand out. Flattening them out unfortunately makes them disappear into the card and loses its interactiveness but I can certainly show you what that looks like.
 
> Finally, I like the label idea to display thermostat state. I can be good to use it to format additional information on others cards like the brightness for light or the speed for fan.

Yeah badges are a great use of status and state. It should be a familiar mental model for many so should help.

> 
> For the first version, I don't think it's a good idea to have multiple controls visible at a time because it will not be possible to have this card integrated in a layout card like this :

I'm totally fine with modes not be available in the first version but I do think it's beneficial for seasonable changes. But given its rarity, I can see that not being a thing at first. However, it does bring more useful to this card for the most likely used actions to interact with the thermostat.

**Comment by antonio1475** [comment]
> What does hvac and preset do?

This is my climate.home status, which is a Tado thermostat.

Hvac modes are pretty obvious. 
Preset mode is home/away

```
hvac_modes:
  - 'off'
  - auto
  - heat
min_temp: 5
max_temp: 25
target_temp_step: 0.1
preset_modes:
  - away
  - home
current_temperature: 18.6
temperature: 18
current_humidity: 53.4
hvac_action: idle
preset_mode: away
offset_celsius: 0.02
offset_fahrenheit: 0.04
icon: mdi:radiator
friendly_name: Casa
supported_features: 17
```

I love your designs btw!

**Comment by andyeskridge** [comment]
I've been following this issue as I am very excited about the potential for a new nice looking climate card. 

To potentially help I've pasted my state below too. 

```yaml
hvac_modes:
  - 'off'
  - auto
  - heat_cool
  - heat
  - cool
min_temp: 55
max_temp: 99
target_temp_step: 1
min_humidity: 35
max_humidity: 65
fan_modes:
  - Auto
  - 'On'
  - Circulate
preset_modes:
  - None
  - Home
  - Away
  - Sleep
current_temperature: 73
temperature: 71
target_temp_high: null
target_temp_low: null
current_humidity: 39
humidity: 50
fan_mode: Auto
hvac_action: idle
preset_mode: None
attribution: Data provided by mynexia.com
zone_status: Idle
dehumidify_supported: true
humidify_supported: false
dehumidify_setpoint: 50
friendly_name: Thermostat NativeZone
supported_features: 31
```

**Comment by brandensilva** [comment]
@antonio1475 @andyeskridge Thanks for sharing your configs. This helps me see more of the capabilities that are possible.

@andyeskridge Does hvac_mode: Auto just do its thing without any user intervention and heat_cool mode allow controlling both low and high temperatures in the range?

How often are you both changing presets per day, week, or month? (I work from home so rarely change from home mode so not something I use at all really since home presence will set it to away if my wife and I are gone)

**Comment by antonio1475** [comment]
> How often are you both changing presets per day

Every time I leave or come home. However, it's done via automation along with everything else, not in the climate card. I am, however, interested in seeing (checking) that it changed to Away when I'm out.

I currently have a template card at the top of my dashboard with all the thermostat info. If I tap it it shows the controls (which I never use. All automated in my case, so I'm probably not the best example)

![FF8268F6-EFBE-4693-B71B-EC0011A2100B](https://user-images.githubusercontent.com/63130724/156666071-69dd04cd-f56b-4d92-80bb-7941fd956c66.jpeg)

**Comment by andyeskridge** [comment]
> @andyeskridge Does hvac_mode: Auto just do its thing without any user intervention and heat_cool mode allow controlling both low and high temperatures in the range?

To tell you the truth, I can't really tell the difference between Auto and heat_cool. They both seem to provide me with the high/low set points.

> How often are you both changing presets per day, week, or month? (I work from home so rarely change from home mode so not something I use at all really since home presence will set it to away if my wife and I are gone)

And there is pretty much always someone in my house, so I haven't dealt with the presets right now.

**Comment by brandensilva** [comment]
@andyeskridge Gotcha. Auto in my mind would act very similar to off mode except that the temperature adjusts on its own. So it's capable of heating or cooling automatically depending on what the thermostat deems is necessary. Not sure if HA supports that though as I haven't ever tried it yet.

If auto mode is possible we'd need auto, dual, heat, cool, and off. That doesn't leave a lot of space for a humidifier and fan icon to fit. 

We might be able to at most fit 6 icons at the minimum allowed column size of HA of 300px. Here is that size in vertical mode for visual reference:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/200190/156789527-b924cc58-d9b0-4e68-86aa-cf5ebee1c94d.png">

I'm thinking that 6th option could be an auxillary pop up to access other less used controls. But given popups are not on the mushroom roadmap any time soon we wouldn't see that for awhile.

**Comment by zsarnett** [comment]
Recommendation: (based on building the first one)

Focus on temperature changing and not mode switching.

Make space for ease of changing the temperature quickly by simple taps. 1 temp or 2 temps (high and low for auto and dual)

Mode can be a click into a dropdown list for example

**Comment by brandensilva** [comment]
@antonio1475 For preset modes I think we could use the icon form to describe those on the main icon for the room/thermostat. Mushroom supports this already with icon badges.

**Comment by andyeskridge** [comment]
I've been playing with the auto mode since I've never used it. I can't tell the difference between Heat/Cool. The physical thermostat actually only has 3 modes (Auto, Heat, and Cool), so when I set it to Heat/Cool it sets the physical thermostat to Auto. 🤷‍♂️ 

I've attached the current default thermostat UI that HA has. 

![image](https://user-images.githubusercontent.com/507452/156790942-f267ac57-d5c2-48fc-87f0-07ba432c724b.png)

Personally, I rarely change modes, so I think the modes should be deemphasized in the design and maybe just a current mode icon.

**Comment by brandensilva** [comment]
> 



> Recommendation: (based on building the first one)
> 
> Focus on temperature changing and not mode switching.

What do you mean here?

> Make space for ease of changing the temperature quickly by simple taps. 1 temp or 2 temps (high and low for auto and dual)

Yeah I'm going to work on that part sometime over the next week when I get a moment.

> Mode can be a click into a dropdown list for example

Right, I mentioned that was my plan for this given some tight space constraints. I'll show this off sometime soon.

@zsarnett What's the difference between auto and heat_cool modes?

**Comment by zsarnett** [comment]
> What do you mean here?
I explained what I meant. Focus on the UX of changing the temperature and less on Modes

> What's the difference between auto and heat_cool modes?

Uh probably nothing but you would need to support switching to either. They both take two temps. PRobably a difference in how they heat and cool

**Comment by brandensilva** [comment]
Gotcha. Yeah I'm going to focus on adjusting temps further as a priority. Still got some deadlines to finish up so might take me a week to get to it.

If we collapse down the action bar due to them being rarely used but in seasonal cases, we should have adequate space in all layout modes.

**Comment by ulic75** [comment]
So I wanted a slider control for my thermostat in UI-Minimalist since I started using it.  However I operate in heat_cool mode, so I needed a slider that supported two controls.  I couldn't find anything that exists that would fit the look and feel, so I built my own only to discover that it doesn't integrate well with button-card.

I was about to start designing my own full on cards that mimic UI-Minimalist when I found Mushroom.  I love it, looks clean, doesn't have multiple layers deep of nested button-cards, but still no climate control.

Regardless, all this to say, if you want  look at my basic design you can find [demos](https://ulic75.github.io/flat-slider/demos) and the [code](https://github.com/ulic75/flat-slider).  I'm not suggesting you use my slider, but if you wanted to or just wanted to take all the code that's cool with me.

![heat_cool_climate_slider](https://user-images.githubusercontent.com/5641964/159794553-282b17ab-e85f-4fb7-8699-27a952045239.png)

**Comment by kevinbegley** [comment]
Hello,

Is there any update on when the climate card might be available?

Thank you,
Kevin

**Comment by ulic75** [comment]
@piitaya I know in repositories how tiresome it can get seeing so many open issues.  Can probably close this one now.

**Comment by bobloadmire** [comment]
is there any update to this? Did anyone get preset modes, or fan modes to work?

**Comment by Swiftnesses** [comment]
Interested in presets too.

**Comment by bobloadmire** [comment]
So I saw they added presents to fans, can you hack the card to work for lights too?

**Comment by toughvj** [comment]
> @andyeskridge Gotcha. Auto in my mind would act very similar to off mode except that the temperature adjusts on its own. So it's capable of heating or cooling automatically depending on what the thermostat deems is necessary. Not sure if HA supports that though as I haven't ever tried it yet.
> 
> If auto mode is possible we'd need auto, dual, heat, cool, and off. That doesn't leave a lot of space for a humidifier and fan icon to fit.
> 
> We might be able to at most fit 6 icons at the minimum allowed column size of HA of 300px. Here is that size in vertical mode for visual reference:
> 
> <img alt="image" width="668" src="https://user-images.githubusercontent.com/200190/156789527-b924cc58-d9b0-4e68-86aa-cf5ebee1c94d.png">
> 
> I'm thinking that 6th option could be an auxillary pop up to access other less used controls. But given popups are not on the mushroom roadmap any time soon we wouldn't see that for awhile.

Is there any code available for that design for climate card?

**Comment by coarsy** [comment]
I currently have the problem, that the AC is always starting in heat-mode. Don't known, why this happens. Is there a way to start the AC in a default mode?

**Comment by deggle** [comment]
I'm also having issues with the climate card (though maybe I'm looking at a different one, as it' doesn't look quite like the one above). It always starts in Heat, not the last known state but also it's showing 3 set point inputs for cases where there should only be one. The official climate card will hide these when I send 'None' via MQTT but the mushroom card shows all three...!?

Any thoughts would be welcome as I much prefer the compact card style.

Many thanks.
