### ISSUE TITLE
[Bug]: actions do not function from within browser_mod popup in v3.0.0

### ISSUE THREAD

**Issue by lichenophile** [piitaya/lovelace-mushroom#1193]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

As of upgrading to v3.0.0:
From within a browser_mod popup, clicking a mushroom card (such as chips, or climate card) the device does not perform it's default action, nor any I attempted to manually set.

Downgrading to v2.8.1 solved my issue.

### Expected Behavior

That actions function.

### Steps To Reproduce

Create a browser_mod popup containing a chip card and set it's `tap_action` to `more-info`

### Environment

```markdown
- Browser: All
- HA Version: 2023.07.1
- Mushroom: v3.0.0
```

### Anything else?

I didn't fiddle around with recreating this issue in a fresh card with no other elements at play (for instance, many  of my popup cards use card_mod), but the effect seemed universal for exclusively mushroom cards within a popup.

Please let me know if you have trouble recreating this issue and I will dig deeper.

**Comment by piitaya** [comment]
Hi 👋
Mushroom use the new `hass-action` for actions since 3.0.0. In this way, we can use the new assist action and we have now styled dialogs for confirmation instead of the browser default one. 

More info in the dev blog : https://developers.home-assistant.io/blog/2023/07/07/action-event-custom-cards

It seems they is an incompatibility with browser_mod. An issue should be open in browser_mod. I will look on my side too to see if I can help on this issue. But at the end, the fix should be in browser_mod. There is nothing we can do on the Mushroom side.
