### ISSUE TITLE
[Bug]: Entity card title font weight 

### ISSUE THREAD

**Issue by ghammer80** [piitaya/lovelace-mushroom#1357]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest Mushroom version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Font weight for the title seems to have changed to regular instead of bold. 

![IMG_0756](https://github.com/piitaya/lovelace-mushroom/assets/43242006/683616d2-0fc9-47ca-b18e-c0b5380f9173)

![IMG_0646](https://github.com/piitaya/lovelace-mushroom/assets/43242006/aac8e2e4-9a5b-470b-893f-5b78c20cc97f)

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Chrome, latest
- HA Version: 2024.1.6
- Mushroom: 3.4.1
```

**Comment by piitaya** [comment]
Hi 👋 Some theme variables have been changed to use the default font style of tile card (https://github.com/piitaya/lovelace-mushroom/pull/1348/files#diff-47d2527b2c38615d2cd4f5c1c06a18c0bdb9b66519e468bba99344b5d9cadd6fR19-R26)
Mushroom support with card mod is not guarantee because it's not officially supported but you can find help in the [community forum](https://community.home-assistant.io/t/mushroom-cards-build-a-beautiful-dashboard-easily/388590)

I close this issue as card mod support is not provided in this repo.
