### ISSUE TITLE
Cover card: Pause button is displayed at all times even if entity don't support that

### ISSUE THREAD

**Issue by martindybal** [piitaya/lovelace-mushroom#149]
**Describe the bug**
The pause button is displayed at all times. It makes no sense to display it if the blind is not moving or the entity does not support SUPPORT_STOP. 

**Expected behavior**
Hide pause button when is not supported

**Describe alternatives you've considered**
Maybe it's a good idea to allow the user to use the buttons as a quick action. Maybe set the blinds to 50%. For example, I use three settings. Blinds fully open, blinds shaded, and blinds darkened. It can be handy for the user to be able to set the behavior of the buttons. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7644099/154893911-cb519c75-d4c6-4018-94ec-2cd53f7ccb96.png)

**Comment by martindybal** [comment]
@piitaya I updated to v1.2.3 and it's not fixed. I still see the pause button

![image](https://user-images.githubusercontent.com/7644099/156366416-705b3678-9f41-4657-b5d2-4d622d278940.png)

**Comment by piitaya** [comment]
What's your entity attributes ?

**Comment by martindybal** [comment]
@piitaya may I founded it somewhere in UI? From component code 
SUPPORT_OPEN | SUPPORT_CLOSE | SUPPORT_SET_POSITION | SUPPORT_OPEN_TILT | SUPPORT_CLOSE_TILT | SUPPORT_SET_TILT_POSITION

**Comment by piitaya** [comment]
`dev tools` => `states` 

 Something like that :

<img width="611" alt="image" src="https://user-images.githubusercontent.com/5878303/156447408-66b38985-4c33-4cd9-a1c4-c489ec3a9ffa.png">

**Comment by martindybal** [comment]
@piitaya `supported_features: 183`

**Comment by piitaya** [comment]
It's strange... The feature is available since `1.2.3` version.

Do you have at least the `1.2.3` version in your browser console ? (I have the `1.2.4` but the feature is available since `1.2.3`)
![image](https://user-images.githubusercontent.com/5878303/156524104-2ec59811-d17a-4e8e-829f-af98bb718caf.png)

Here what I have with `supported_features: 183` :
![image](https://user-images.githubusercontent.com/5878303/156524286-fa8e28c5-2750-47d1-9bdd-ec8cf15bb1ac.png)
<img width="419" alt="image" src="https://user-images.githubusercontent.com/5878303/156524306-d8e279ea-7b57-4c2d-9822-2cce20af86f1.png">

**Comment by martindybal** [comment]
![image](https://user-images.githubusercontent.com/7644099/156552365-a67d4062-35b2-486b-8a17-c4b3c4e48820.png)
![image](https://user-images.githubusercontent.com/7644099/156552403-7c53bbbf-f0b3-4039-afe4-e296eed724fc.png)
![image](https://user-images.githubusercontent.com/7644099/156552473-20ee31f5-671d-4f91-b0a5-dc48b482ba41.png)

**Comment by piitaya** [comment]
Ok, it was just a cache issue 😅
