### ISSUE TITLE
Themes are not applied

### ISSUE THREAD

**Issue by Serhioromano** [piitaya/lovelace-mushroom#164]
Lok, it is a beautiful layout cards. I like it very match.  But the fact that themes are not applied there is a shame. If I build the whole dashboard with mushroom cards only that might work, although it is practically impossible, but even those you would be stack with single theme.

To me it misses so much goodness to be blended into HA seamlessly and adopt all themes like it was there from the start.

Is it possible to do that?

**Comment by antonio1475** [comment]
I can't understand what you're saying, but you might want to install mushroom **theme** ([link](https://github.com/piitaya/lovelace-mushroom-themes)) and apply it to your user settings and/or each Dashboard page/tab, **for the rest of the cards to have a Mushroom style**. You also have the Mushroom Square option.

If you want mushroom cards to have another theme... I don't really see the point in that - I  believe Mushroom cards are special partially because of their theme. Plus it's probably really complicated to accommodate to other themes.

**Comment by piitaya** [comment]
Mushroom use text and background color from HA theme. 
Do you have an example (screenshot) of theme not applied ?

**Comment by Serhioromano** [comment]
Here are 2 examples, 2 light switches in a greed in a vertical stack. Dark is whatsapp theme, light is iOS theme. 

![2022-02-28_18-48-35](https://user-images.githubusercontent.com/650741/155986203-3efd1961-f746-4e83-aa1e-fe10f21c6df4.png)
![2022-02-28_18-47-36](https://user-images.githubusercontent.com/650741/155986211-367544f6-b09b-4674-bfa3-96d12a647741.png)

Although it is not like this always. On the other tab I add a few controls and it looks good.

![2022-02-28_18-53-24](https://user-images.githubusercontent.com/650741/155986802-ba290259-3cba-4a68-b27d-91f2d4528902.png)

**Comment by piitaya** [comment]
I tested with whats app theme too and I have no issue :
<img width="545" alt="image" src="https://user-images.githubusercontent.com/5878303/156455846-3ddb8bb6-58fc-44e1-b068-8cf173708552.png">

How do you apply the theme ?
- from the profile ?
- from the view ?

There can be issues if you use both settings.

**Comment by Serhioromano** [comment]
I use only one profile setting for theme.

**Comment by KTibow** [comment]
@Serhioromano are you still experiencing this? Have you tried reloading the page?

**Comment by Serhioromano** [comment]
It sometimes there sometimes not. I have no control over it. SO I just used another theme.
