### ISSUE TITLE
Invert position on Cover card

### ISSUE THREAD

**Issue by tuxmeister** [piitaya/lovelace-mushroom#171]
**Is your feature request related to a problem? Please describe.**
Mushroom cover card currently interprets 100% as Open, 0% as Closed. I would like to reverse these positions, if I reduce the slider, cover should go up. Right now it goes down. 

**Describe the solution you'd like**
Ability to reverse the cover slider so that 0% is Open and 100% is Closed,.

**Describe alternatives you've considered**
I was using the Custom Slider card before, which allows to "invert" the slider. 

Thank you so much for the work so far! Loving this!

**Comment by piitaya** [comment]
Hi 🙂
Home Assistant use [100% for open and 0% for closed](https://developers.home-assistant.io/docs/core/entity/cover/#platform-properties-to-be-implemented-by-deriving-platform-classes). 
We strive to stay as close as possible to the concepts of home assistant so that mushroom is the most accessible and easy to use.

**Comment by Janthenman67** [comment]
I had the same issue (also in HA). It can easily be solved with a template. Let me know if you would like to have the yaml

**Comment by KTibow** [comment]
@tuxmeister can you close this issue as it's fixable via a template cover, and your cover is nonstandard?

**Comment by tuxmeister** [comment]
Sure! I still haven't figured out how to do it, but I remember doing something similar for some plugs once.
