### ISSUE TITLE
[Feature]: Add groups to light control card

### ISSUE THREAD

**Issue by CoreyJ87** [piitaya/lovelace-mushroom#673]
### Is your feature request related to a problem?

Cant seem to control brightness on groups

### Describe the solution you'd like

I have alot of my lights in groups. and I want to be able to control them with the brightness slider. I dont know if this is possible. I know groups act a bit differently in HASS than a light entity. But is there no way to just send brightness details to any light entity inside the group. and just ignore the rest?

**Comment by piitaya** [comment]
How do you setup your group?
Using this integration https://www.home-assistant.io/integrations/group/ ?
It should work as a light 😊

**Comment by CoreyJ87** [comment]
Yeah sorry @piitaya didnt do enough research before posting. thanks

**Comment by fufish** [comment]
I have the same issue with the following procedure: I create and update the group within an automation (it only includes the currently active lights)
`service: group.set
data:
  name: All Active Lights Auto
  object_id: all_active_lights_auto
  icon: mdi:lightbulb-group
  entities: >
    {{ expand(states.light) | selectattr('state','eq','on') |
    map(attribute='entity_id') | list }}`
The resulting group is available via "group.all_active_lights_auto". This group won't be registered by the mushroom card as a light or light group with all its features although in the more-info-frontend it looks very similar feature wise. I'd love to use the mushroom brightness- and color temperature-controls for that one but I can't get it to work. I'd also be totally fine with changing the automation code so that the group automatically correctly registers as a light group or updates an existing light group but I also couldn't get that to work for now. Do you have an idea?
