### ISSUE TITLE
Disable haptic feedback (vibration) on andriod device

### ISSUE THREAD

**Issue by Eivind-V** [piitaya/lovelace-mushroom#93]
When using [chips](https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/chips.md) and [light card](https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/light.md) on Andriod device I get a haptic feedback.

Have disabled it under profile settings
![image](https://user-images.githubusercontent.com/97055129/153491080-5e9ff0f2-08d3-4079-a071-cdef7fd1fccb.png)

![image](https://user-images.githubusercontent.com/97055129/153490976-6ece33d4-4478-4b73-a8e7-0fe256713026.png)

**Comment by bernikr** [comment]
I have the same problem, that even with vibration turned "off" in the options the cards will vibrate on toggle.

**Comment by bernikr** [comment]
> It's the native thing from home assistant toggle service, not a Mushroom feature.

Its not native to the home assistants toggle service, but to the custom-card-helper `handleAction` method.

I've raised an issue there: custom-cards/custom-card-helpers#61

I hope this can be resolved. I would really like to use the mushroom cards, but having my phone vibrate for 2 seconds every time I toggle something is not really the best experience.

**Comment by piitaya** [comment]
Can you provide some details about your phone/android version/HA Android version ? I have no issue with my OnePlus 8. So I unable to reproduce ce bug.

**Comment by bernikr** [comment]
Sure:
Phone: Huawei Mate 20 (HMA-L29)
Android Version: 10
HA Version: 2022.3.8
App Version: 2022.3.0-full

I also noticed that the vibration changes depending if they are turned on or turned off/phone is in "do not disturb" mode. When the vibrations are turned off it changes from two short pulses to a single 500ms pulse, which is way more annoying.

I suspect that there is a bug in the android app itself, since I found code there that is responsible for a 500ms vibration. I've also raised an issue there: home-assistant/android#2430

**Comment by piitaya** [comment]
I looked into the `custom-card-helpers` and the home-assistant-frontend code. Custom card helpers use `success` haptics while HA native cards use `light` ones.

**Comment by bernikr** [comment]
I saw that and wrote that into the issue i opened there. However, I think it is mostly a problem with the android app under certain conditions, as disabling vibrations works well in the mobile browser. Lets hope it gets fixed there soon.

**Comment by bernikr** [comment]
You could btw use `handleClick` instead of `handleAction` of the custom-card-helpers. It has a slightly different function signature (two booleans instead of one string for the action), but allows the user to define a `haptics` setting, instead of always emitting a `success` event on toggle or service call.

**Comment by piitaya** [comment]
`custom-card-helpers` is no longer maintained. I will import the handle-action into mushroom to keep it updated with home assistant action.

**Comment by bernikr** [comment]
After a bit more code reading and long discussion (home-assistant/android#2430), i _think_ the problem is that the `custom-card-helpers` emit their haptics directly on the `window`, while all native HA cards emit it on their respective DOM element. I still don't understand the chain of bugs and undocumented things that lead to this strange behavior in the end, but this seems to be the only difference on how native HA cards and `custom-card-helpers` implement the haptics.

**Comment by gmac0612** [comment]
I have tried this today and encountered similar behaviour. Haptic setting in companion app is not respected & all taps provide a long 'success' vibration.

HA and companion app both latest stable as of time of writing, handset is a Samsung Galaxy S8+

I'd be very happy to see this fixed as the cards are perfect apart from this issue.

**Comment by dafer94** [comment]
I am suffering the same behaviour described by Bernikr a few comments above, also with the same Huawei device: The haptics for custom cards does not turn off when the app toggle is disabled, they just change from two shorts pulses to a long one.

I have also tested it with an older device (OnePlus 3). The exact same dashboard with the same app settings and it works just fine.

Have somebody found a workaround for this? Maybe a dashboard setting that makes it quiet and prevent its inner cards from generating haptic feedback.

**Comment by nelsonamen** [comment]
Same problem, ONLY in mushrooms, vibrations always on

**Comment by filikun** [comment]
This seems to be the same on iPhone. I even tried the haptic parameter

'''
        tap_action:
          action: call-service
          service: input_select.select_option
          haptic: light
          service_data:
            entity_id: input_select.chart_time_span
            option: day
'''

**Comment by piitaya** [comment]
It should be fixed in the [1.9.0 beta version](https://github.com/piitaya/lovelace-mushroom/releases/tag/v1.9.0). Can you confirm it works now ?
@gmac0612 @Eivind-V @bernikr @dafer94 @nelsonamen

**Comment by nelsonamen** [comment]
It works!! 👍

**Comment by bernikr** [comment]
It's fixed now. Thanks!!
