### ISSUE TITLE
[Feature]: More precise slider movements for touch input

### ISSUE THREAD

**Issue by phischdev** [piitaya/lovelace-mushroom#934]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

It is hard to do fine-grained changes to sliders by touch on a small device like a smartphone.
Hitting exactly 1% (instead of 0%) or other small values requires many tries.

While during day-time a difference of few percentages points aren't noticeable, at night in a low-light setting, the difference between 1% or 4% brightness of a main light source makes a strong perceivable difference. 
Even more so, choosing a color from the color band is difficult to do precisely.

### Describe the solution you'd like

Instead of having to hit the absolute value by finger (like the left-most pixel of the slider for 0%), the slider could be moved relatively at lower speed. 

Example: the slider is at 10%. The finger touches down anywhere on the right half of the slider and moves to towards the left. The value is then decreased by half the way the finger travelled.

This would allow for precise placement of the slider. Similar to how scrubbing works in many smartphone apps like the audible player.

### Describe alternatives you've considered

Instead of the slide speed being fixed at eg. 50% it could be adjusted by dragging the finger downwards like many other apps do.

### Additional context

I hope the description of the problem and the solution are understandable. 

I already implemented this solution and was about to create a PR when I saw it requires creating an issue first.
It can be found here (https://github.com/piitaya/lovelace-mushroom/pull/935)

Notice: The changes only affect the panning (pointer down, move, pointer up). Clicking/Tapping an absolute value still works like before.

**Comment by piitaya** [comment]
I don't think we should add this type of control. If you move your finger from 30px, the slider should move by 30px. 

The proper way to have more precise control is to use a full screen slider like this one :
![CleanShot 2023-01-09 at 17 08 25](https://user-images.githubusercontent.com/5878303/211354163-5c2fc054-a76d-484e-b462-9785db38fa2b.png)

**Comment by milandzuris** [comment]
> I don't think we should add this type of control. If you move your finger from 30px, the slider should move by 30px.
> 
> The proper way to have more precise control is to use a full screen slider like this one : ![CleanShot 2023-01-09 at 17 08 25](https://user-images.githubusercontent.com/5878303/211354163-5c2fc054-a76d-484e-b462-9785db38fa2b.png)
When is release date for new HA cards and other dashboards things?

**Comment by phischdev** [comment]
hey @piitaya, thank you for your answer and for looking into it so quickly.
I see that you're heading for a solution like implemented by Apple's HomeKit, so maybe let's discuss my approach in two parts:

1. Relative Movement:
I think it's easy to see that even when moving the slider at the same speed as the finger, there is much better control of it, if it's possible to drag and move the slider from any position instead of moving the finger at the exact position needed to set a certain value. Apple even implemented it in the same way for the vertical slider you reference above.

2. Reduced Slide Speed vs Overlay:
"If you move your finger from 30px, the slider should move by 30px. The proper way to have more precise control is to use a full screen slider like this one"
I would disagree with that statement in general. Both are different approaches for solving the issue. They are being used by other apps and have their own drawbacks and advantages.
Personally, I always liked the mushroom cards because of their convenience and efficiency: The values are editable in place, on the dashboard without the need for additional overlays and more clicks. It's so quick to open the app, slide down the brightness of a light and close it again. (Unlike with Apple's HomeKit) 
I've been using my approach of 50% pan speed for a few days and have to say it made things a lot easier on phone and tablet and feels like a natural improvement to the mushroom cards without taking anything away.

**Comment by piitaya** [comment]
1. Yes, some apps like Apple Home use relative instead of absolute. It's a bit disconcerting when you use to use absolute before. All Home Assistant slider are absolute for now. That's why I preferred to keep the same usage.
2. I like to use quick shortcuts to edit brightness or something else too. But IMO, it should be quick actions, not precise brightness adjustment. A fullscreen experience is preferable for that.

I agree that `1%` brightness is hard to reach. There are already issues for this. We can set the minimal to `1%` instead of `0`% to fix that issue so it's easy to set the minimal value for a light.

**Comment by igoro00** [comment]
My lamp is very noticeably dimmer at 1% than any other setting. 2% and 4, even 5% - not much difference. 1% and 2% - like night and day(pun not intended). 

I usually like my light at 1% so a simple toggle in the card settings like "Turn off with brightness slider?" that's setting the min slider value to either 0% and 1% would be great

**Comment by mikedrawback** [comment]
The option to set a min and max range for sliders would be great

**Comment by Skeptomenos** [comment]
As someone who frequently adjusts sliders on a small device, I know how frustrating it can be to hit the exact value I want. This new solution of being able to move the slider relatively with more precision will be a game-changer.

Not only will it make adjusting sliders easier, but it will also allow for more control and accuracy when making important adjustments, like setting the brightness or color in a low-light setting. The ability to adjust the speed by dragging the finger downwards is also a great touch and makes the feature even more customizable. I would love to try this feature out for myself and see the improved user experience firsthand. 

However, I also understand that the vision for the Mushroom extension is important to maintain consistency in its user experience. That's why I suggest making the new feature of relative slider control optional in the settings. This way, users who prefer the traditional way of adjusting sliders can continue to do so, while those who would benefit from the added precision can easily turn the feature on.

By making this feature optional, you can still maintain the original vision for the extension while providing additional value to users who need it. I believe this is a win-win solution that will allow the original developer to stay true to their vision while still incorporating useful and requested features.

**Comment by phischdev** [comment]
I decided to fork the project and bring it to HACS as ["Mushroom Better Sliders"](https://github.com/phischdev/lovelace-mushroom-better-sliders)

**Comment by basnijholt** [comment]
I’m using the fork now (which is bound to get out of sync.)

Wouldn’t it be possible to make this control method configurable?

in this way, we avoid splitting off this package. 

@piitaya, @phischdev
